@crud-api-host = http://localhost:5190/api

### Get all profiles
GET {{crud-api-host}}/profile/getall

### Get all employees
GET {{crud-api-host}}/employee/getall

### Get one employee by id
GET {{crud-api-host}}/employee/getbyid/21

### Create new employee
POST {{crud-api-host}}/employee/create/
Content-Type: application/json

{
  "FullName": "Kenny",
  "Salary": 1200,
  "IdProfile": 3
}

###

PUT {{crud-api-host}}/employee/update/35
Content-Type: application/json

{
  "id": 35,
  "FullName": "John Beltrán",
  "Salary": 120,
  "IdProfile": 2
}

###

DELETE {{crud-api-host}}/employee/delete/29

###