@crud-api-host = http://localhost:5190

### Get all profiles
GET {{crud-api-host}}/profile/list

### Get all employees
GET {{crud-api-host}}/employee/list

### Get one employee by id
GET {{crud-api-host}}/employee/list/26

### Create new employee
POST {{crud-api-host}}/employee/create
Content-Type: application/json

{
  "FullName": "Kenny",
  "Salary": 1200,
  "IdProfile": 3
}

###

PUT {{crud-api-host}}/employee/edit
Content-Type: application/json

{
  "id": 26,
  "FullName": "Nuevos cambios",
  "Salary": 90,
  "IdProfile": 2
}

###

DELETE {{crud-api-host}}/employee/delete/27

###